version: '3.3'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 8888:80
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel
      - pensa-network

  mysql:
    image: library/mysql:8.0.23
    command: mysqld --sql_mode="" --log_bin_trust_function_creators=1 --default-authentication-plugin=mysql_native_password
    container_name: mysql
    environment:
      MYSQL_DATABASE: '${DB}'
      MYSQL_USER: '${USERDB}'
      MYSQL_PASSWORD: '${DOCKER_PASSDB}'
      MYSQL_ROOT_PASSWORD: '${DOCKER_PASSDB}'
    ports:
      - 33069:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - laravel
      - pensa-network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    environment:
      ENC_PATCH: '/var/www/html/'
      ENC_KEY: '${ENC_KEY}'
    volumes:
      - .:/var/www/html
    ports:
      - 9000:80
    networks:
      - laravel
      - pensa-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 15672:15672
    networks:
      - laravel
      - pensa-network

networks:
  laravel:
  pensa-network:
    external: true
